language: go

services:
  - docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

go:
  - "1.10.x"

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - make dependencies

stages:
  - name: validate and build
  - name: release to github
    if: tag IS present
  - name: push to dockerhub
    if: tag IS present

jobs:
  include:
    # validate and build
    - stage: validate and build
      script:
        - make test
        - make lint
        - make coverage
        - make validate-commit
    - script:
      - docker run -d --name bblfshd --privileged --volume $HOME/bblfsh-drivers:/var/lib/bblfshd -p "9432:9432" bblfsh/bblfshd
      - sleep 5
      - docker exec -it bblfshd bblfshctl driver install go docker://bblfsh/go-driver:latest
      - docker exec -it bblfshd bblfshctl driver install javascript docker://bblfsh/javascript-driver:latest
      - mkdir $HOME/repos
      - git clone https://github.com/src-d/gitbase-playground.git $HOME/repos/gitbase-playground
      - docker run -d --name gitbase -p "3367:3306" -e "BBLFSH_ENDPOINT=bblfshd:9432" --volume $HOME/repos:/opt/repos --link bblfshd srcd/gitbase
      - sleep 15
      - GITBASEPG_DB_CONNECTION='gitbase@tcp(localhost:3367)/none' GITBASEPG_INTEGRATION_TESTS=true make test
    - script:
        - make packages
    # release to github
    - stage: release to github
      script:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          all_branches: true

cache:
  directories:
    - $HOME/bblfsh-drivers/images

before_cache:
  # make bblfsh images readable
  - sudo chmod -R 777 $HOME/bblfsh-drivers/images
